language: c
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - ocaml
    - ocaml-native-compilers
    - opam
    - aspcud

script: ./.travis-ci.sh
env:
  - OPAM_SWITCH=4.05.0
  - OPAM_SWITCH=4.06.1
  - OPAM_SWITCH=4.07.1
  - OPAM_SWITCH=4.08.1
  - OPAM_SWITCH=4.09.1
  - OPAM_SWITCH=4.10.0
# cache:
#   directories:
#   - $HOME/.opam
