language: c
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - ocaml
    - ocaml-native-compilers
    - opam
    - aspcud
    - nettle-dev   # for ocamlnet

script: bash -ex .travis-ci.sh
env:
  - OPAM_SWITCH=4.02.3
  - OPAM_SWITCH=4.03.0
  - OPAM_SWITCH=4.04.2
# cache:
#   directories:
#   - $HOME/.opam
