language: c
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - ocaml
    - ocaml-native-compilers
    - opam
    - aspcud
    - libgnutls28-dev
    - nettle-dev   # for ocamlnet

script: ./.travis-ci.sh
env:
  - OPAM_SWITCH=4.05.0
  - OPAM_SWITCH=4.06.1
  - OPAM_SWITCH=4.07.1
  - OPAM_SWITCH=4.08.1
# cache:
#   directories:
#   - $HOME/.opam
